### ISSUE TITLE
Update Gondor pack with dragon egg

### ISSUE THREAD

**Issue by LimeeFox** [EpicQuestz/EpicQuestz-RPs#26]
In Eriador Pack v0.8, I added @the-pharaohs-cat's dragon egg cobblestone texture, from commit `de865ca9b690079642ab0a6cb3fbd63796187b14`. I didn't begin updating the Gondor pack yet, but this is a to-do issue for whoever is going to do it (even if it is myself!)

**Comment by Tobberz** [comment]
This seems to be done
