### ISSUE TITLE
Sea Pickles -> candles

### ISSUE THREAD

**Issue by LimeeFox** [EpicQuestz/EpicQuestz-RPs#8]
On many maps, sea pickles have been used as candles with this thought in mind: it will be retextured to whatever texture candles usually have.

**Comment by StealWonders** [comment]
1.17 has candles. I suggest not using sea pickles.

**Comment by Tobberz** [comment]
> 1.17 has candles. I suggest not using sea pickles.

I agree with Steal here, closed.
